---
output:
  html_document: default
  pdf_document: default
---
## DataFrame
```{r}
# How to create a data frame
a <- c(10,20,30,40)
b <- c('book', 'pen', 'textbook', 'pencil_case')
c <- c(TRUE,FALSE,TRUE,FALSE)
d <- c(2.5, 8, 10, 7)
# Join the variables to create a data frame
df <- data.frame(a,b,c,d)
df
```
## Name the columns in the data frame
```{r}
names(df) <- c('ID', 'items', 'store', 'price')
df
```
## Print the structure
```{r}
str(df)
```
## Slice Data Frame
```{r}
# Select the value in row 1 of column 2
df[1,2]
```
```{r}
# Select Rows 1 to 2
df[1:2,]

```
```{r}
# Select Columns 1
df[,1]

```
```{r}
# Select Rows 1 to 3 and columns 3 to 4
df[1:3, 3:4]

```
```{r}
# Slice with columns name
df[, c('ID', 'store')]
```
## Append a Column to Data Frame
```{r}
# Create a new vector
quantity <- c(10, 35, 40, 5)

# Add `quantity` to the `df` data frame
df$quantity <- quantity
df
```
## Select a column of a data frame
```{r}
# Select the column ID
df$ID
```
## Subset a data frame
```{r}
subset(df, subset = price > 5)
```

